### ISSUE TITLE
hiccup-cli not found in Melpa repository

### ISSUE THREAD

**Issue by mrivas616** [kwrooijen/hiccup-cli#2]
The hiccup-cli package is not found when trying to install it via `M-x package-install hiccup-cli`. The same goes when looking up the package directly in melpa.org search bar, only package found is html-to-hiccup.

![image](https://user-images.githubusercontent.com/7102571/106516852-45e1c880-649d-11eb-95cc-b8044a7aba24.png)

![image](https://user-images.githubusercontent.com/7102571/106516728-19c64780-649d-11eb-895e-f9b895a638f0.png)

Has the package been taken down?

**Comment by kwrooijen** [comment]
Sorry, It's in review right now https://github.com/melpa/melpa/pull/7387 :grimacing:

**Comment by mrivas616** [comment]
> Sorry, It's in review right now [melpa/melpa#7387](https://github.com/melpa/melpa/pull/7387) grimacing

Gotcha, sorry I didn't check first.
Thank you :)

**Comment by kwrooijen** [comment]
No problem, I didn't think it would take this long to get it merged. I'll close this once it's on MELPA and you'll be notified.

**Comment by kwrooijen** [comment]
It's on Melpa now https://melpa.org/#/hiccup-cli
(Not you still need to compile the cli locally, still need to figure out how to do that using CI/CD)
