### ISSUE TITLE
Using hiccup-cli with vim/neovim

### ISSUE THREAD

**Issue by humorless** [kwrooijen/hiccup-cli#4]
## Installation and configuration

1. Download the `hiccup-cli` binary from [here](https://github.com/kwrooijen/hiccup-cli/releases). 
2. Move `hiccup-cli` to `/usr/local/bin/hiccup-cli`
3. Because the `hiccup-cli` does not support reading from stdin, I need to configure it with a bash script `html2hiccup`.
```
#!/usr/bin/env bash

middle="$(mktemp)"
while IFS= read -r line; do
    echo "$line" >> "$middle"
done

hiccup-cli --html-file "$middle"
```
Move the script `html2hiccup` to `/usr/local/bin/html2hiccup`

## Screenshots

[vim reference with external command](https://learnvim.irian.to/basics/external_commands#filtering-texts)
<img width="695" alt="before" src="https://github.com/kwrooijen/hiccup-cli/assets/3061798/925c2cf0-0787-497e-9ba3-a7a8ca88c41f">
<img width="692" alt="after" src="https://github.com/kwrooijen/hiccup-cli/assets/3061798/df4478db-4a25-468b-9cb1-2c1ff8aed82d">

**Comment by kwrooijen** [comment]
What is it that you'd like me to with this issue? What is your request exactly?

**Comment by humorless** [comment]
Hi @kwrooijen, 

When I first saw `hiccup-cli`, I thought I would like to use it with vim. However, it still needed more effort to integrate it with vim. I tried my way and posted it here. 

I am not sure if it is the best way to integrate `hiccup-cli` with vim. Probably, other people would provide better idea. 

Feel free to close it. My issue is to share my integration method.

**Comment by kwrooijen** [comment]
I'll add a Vim section to the README so other people can find your solution. I don't have any knowledge of Vim so it's hard for me to really comment on this. But apparently it works so it's good enough for me. Thanks!
